### ISSUE TITLE
Server crashes with mod installed

### ISSUE THREAD

**Issue by BeyondTheStarss** [Team-Abode/Cave-Enhancements#1]
[latest.log](https://github.com/Team-Abode/Cave-Enhancements/files/10677789/latest.log)
I have no idea *why* it crashes except for something to do with entrypoints
This is running on a self-hosted server for fabric 1.19.2, if self hosting changes anything
can provide mod list if needed and sorry if this is an awful report, I don't do this often.

EDIT: Rewording a bit, it doesn't crash, it just doesn't let the server boot up. fun isn't it?

**Comment by ExDrill** [comment]
Thank you for reporting, I know the exact issue and a hotfix will roll out soon.

**Comment by BeyondTheStarss** [comment]
> Thank you for reporting, I know the exact issue and a hotfix will roll out soon.

Thank you for fixing it! I'm glad ill be able to run it in my server!
