### ISSUE TITLE
Placed redstone recievers cause game to get stuck on the saving world screen

### ISSUE THREAD

**Issue by YamBaron** [Team-Abode/Cave-Enhancements#2]
When placing down any type of redstone receiver and quitting out of the world, the game will get stuck on the "saving world" screen. the game isn't frozen while doing this, but It stays on this screen until it is forced to close. This happens regardless of dimension or if the chunk with the redstone receiver is loaded.

I first encountered this on forge 43.2.3 with a handful of other mods. I later did some testing In 43.2.4 with only cave enhancements and confirmed the presence of the same issue.

**Comment by ExDrill** [comment]
They seemed to work just fine on my dev environment on 43.2.0, I'll check and see if this is a Cave Enhancements issue or more of a Forge one.

**Comment by ExDrill** [comment]
Fixed it, thank you for reporting. The update should be launching soon!
